version: '3.8'

services:
  db:
    image: postgres
    container_name: stride4health_db
    environment:
      POSTGRES_DB: stride4health_db
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

